
let ourTeam =[
    {name:"Wayne Barnett",
    role:"founder & CEO",
    img: "wayne-barnett-founder-ceo",
    }, 
    {name:"Angela Caroll",
    role:"Chief Editor",
    img: "angela-caroll-chief-editor.jpg",
    }, 
    {name:"Walter Gordon",
    role:"Office Manager",
    img: "walter-gordon-office-manager.jpg",
    }, 
    {name:"Angela Lopez",
    role:"Social Media Menager",
    img: "angela-lopez-social-media-menager.jpg",
    },  
    {name:"Scott Estrada",
    role:"Developer",
    img: "scott-estrada-developer.jpg",
    },  
    {name:"Barbara Ramos",
    role:"Graphic Designer",
    img: "barbara-ramos-graphic-designer.jpg",
    },   
]

